package org.ddolib.common.solver.stat;

/**
 * Class tracking statistics specifics to A* variants
 */
public class AstarSearchStatistics extends SearchStatistics {

    /**
     * The Exponential Moving Average (EMA) of the ratio of children added to the priority queue (open)
     * compared to the total number of children generated.
     * Initialized to 1.0 (optimistic value) to account for the initial warm-up phase.
     */
    private double _validChildrenRatio = 1.0;

    /**
     * Constructs a new SearchStatistics instance.
     *
     * @param startTime the start time of the search (in milliseconds)
     * @param initValue the initial value for the incumbent
     */
    public AstarSearchStatistics(long startTime, double initValue) {
        super(startTime, initValue);
    }

    @Override
    public AstarSearchStatistics copy() {
        AstarSearchStatistics clone = (AstarSearchStatistics) super.copy();
        clone._validChildrenRatio = this._validChildrenRatio;
        return clone;
    }

    /**
     * Retrieves the current Exponential Moving Average (EMA) of the novelty ratio.
     * A value close to 0.0 indicates that the algorithm is generating a massive amount
     * of redundant or suboptimal states, signaling probable stagnation.
     *
     * @return the smoothed ratio value (theoretically between 0.0 and 1.0)
     */
    public double validChildrenRatio() {
        return _validChildrenRatio;
    }

    /**
     * Calculates the local novelty ratio for the current iteration and updates
     * the Exponential Moving Average (EMA).
     * <p>
     * The smoothing is performed with a default alpha factor of 0.05.
     * If no children were generated, the EMA is not modified to prevent division by zero.
     * </p>
     *
     * @param nbGeneratedChildren the total number of children generated by the transition function
     * @param nbSelectedChildren  the number of relevant children (not pruned by upper bound and not in closed list)
     * @return a new instance with updated validChildrenRation
     */
    public AstarSearchStatistics updateValidChildrenRatio(int nbGeneratedChildren, int nbSelectedChildren) {
        if (nbSelectedChildren == 0) return this;

        AstarSearchStatistics toReturn = this.copy();
        double r = (double) nbSelectedChildren / nbGeneratedChildren;
        double alpha = 0.05;
        toReturn._validChildrenRatio = alpha * r + (1 - alpha) * this._validChildrenRatio;
        return toReturn;
    }


}
