package org.ddolib.common.solver.stat;

/**
 * Class tracking statistics specific to A* variants
 */
public class AstarStats extends SearchStatistics {

    /**
     * The Exponential Moving Average (EMA) of the ratio of children added to the priority queue (open)
     * compared to the total number of children generated.
     * Initialized to 1.0 (optimistic value) to account for the initial warm-up phase.
     */
    private double _validChildrenRatio = 1.0;

    /**
     * Constructs a new SearchStatistics instance.
     *
     * @param startTime the start time of the search (in milliseconds)
     * @param initValue the initial value for the incumbent
     */
    public AstarStats(long startTime, double initValue) {
        super(startTime, initValue);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected AstarStats createSpecificInstance() {
        AstarStats clone = new AstarStats(this._startTime, this._incumbent);
        clone._validChildrenRatio = this._validChildrenRatio;
        return clone;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats copy() {
        AstarStats clone = (AstarStats) super.copy();
        clone._validChildrenRatio = this._validChildrenRatio;
        return clone;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats updateIncumbent(double incumbent, double gap) {
        return (AstarStats) super.updateIncumbent(incumbent, gap);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats updateStatus(SearchStatus status) {
        return (AstarStats) super.updateStatus(status);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats incrementNbIter() {
        return (AstarStats) super.incrementNbIter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats updateFrontierMaxSize(int frontierSize) {
        return (AstarStats) super.updateFrontierMaxSize(frontierSize);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats incrementFrontierSize() {
        return (AstarStats) super.incrementFrontierSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats updateGap(double gap) {
        return (AstarStats) super.updateGap(gap);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats updateTime(long time) {
        return (AstarStats) super.updateTime(time);
    }

    /**
     * Retrieves the current Exponential Moving Average (EMA) of the novelty percentage.
     * A value close to 0.0 indicates that the algorithm is generating a massive amount
     * of redundant or suboptimal states, signaling probable stagnation.
     *
     * @return the smoothed ratio value (theoretically between 0 % and 1 %)
     */
    public double validChildrenPercent() {
        return 100 * _validChildrenRatio;
    }

    /**
     * Calculates the local novelty ratio for the current iteration and updates
     * the Exponential Moving Average (EMA).
     * <p>
     * EMA is a type of moving average that places a greater weight on the most recent data points,
     * providing a smoothed trend of the ratio over time while remaining responsive to recent changes.
     * By smoothing the data, it is less sensitive to extreme local variations—such as nodes with 
     * zero or a sudden surge of selected children—resulting in a more stable and reliable indicator 
     * of the search efficiency.
     * The smoothing is performed with a default alpha factor of 0.05.
     * If no children were generated, the EMA is not modified to prevent division by zero.
     * </p>
     *
     * @param nbGeneratedChildren the total number of children generated by the transition function
     * @param nbSelectedChildren  the number of relevant children (not pruned by upper bound and not in closed list)
     * @return a new instance with updated validChildrenRatio
     */
    public AstarStats updateValidChildrenPercent(int nbGeneratedChildren, int nbSelectedChildren) {
        if (nbSelectedChildren == 0) return this;

        AstarStats toReturn = this.copy();
        double r = (double) nbSelectedChildren / nbGeneratedChildren;
        double alpha = 0.05;
        toReturn._validChildrenRatio = alpha * r + (1 - alpha) * this._validChildrenRatio;
        return toReturn;
    }


}
