package org.ddolib.common.solver.stat;

/**
 * Class tracking statistics specific to A* variants
 */
public class AstarStats extends SearchStatistics<AstarStats> {

    /**
     * The Exponential Moving Average (EMA) of the ratio of children added to the priority queue (open)
     * compared to the total number of children generated.
     * Initialized to 1.0 (optimistic value) to account for the initial warm-up phase.
     */
    private double _validChildrenRatio = 1.0;

    /**
     * Constructs a new SearchStatistics instance.
     *
     * @param startTime the start time of the search (in milliseconds)
     * @param initValue the initial value for the incumbent
     */
    public AstarStats(long startTime, double initValue) {
        super(startTime, initValue);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected AstarStats createSpecificInstance() {
        AstarStats clone = new AstarStats(this._startTime, this._incumbent);
        clone._validChildrenRatio = this._validChildrenRatio;
        return clone;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AstarStats copy() {
        AstarStats clone = super.copy();
        clone._validChildrenRatio = this._validChildrenRatio;
        return clone;
    }

    /**
     * Retrieves the current Exponential Moving Average (EMA) of the novelty percentage.
     * A value close to 0.0 indicates that the algorithm is generating a massive amount
     * of redundant or suboptimal states, signaling probable stagnation.
     *
     * @return the smoothed ratio value (theoretically between 0 % and 1 %)
     */
    public double validChildrenPercent() {
        return 100 * _validChildrenRatio;
    }

    /**
     * Calculates the local novelty ratio for the current iteration and updates
     * the Exponential Moving Average (EMA).
     * <p>
     * The smoothing is performed with a default alpha factor of 0.05.
     * If no children were generated, the EMA is not modified to prevent division by zero.
     * </p>
     *
     * @param nbGeneratedChildren the total number of children generated by the transition function
     * @param nbSelectedChildren  the number of relevant children (not pruned by upper bound and not in closed list)
     * @return a new instance with updated validChildrenRatio
     */
    public AstarStats updateValidChildrenPercent(int nbGeneratedChildren, int nbSelectedChildren) {
        if (nbSelectedChildren == 0) return this;

        AstarStats toReturn = this.copy();
        double r = (double) nbSelectedChildren / nbGeneratedChildren;
        double alpha = 0.05;
        toReturn._validChildrenRatio = alpha * r + (1 - alpha) * this._validChildrenRatio;
        return toReturn;
    }


}
