name: Javadoc
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed
jobs:
  javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        maven: ['3.8.5']
        java: ['21']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.java }}-

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Generate Javadoc
        run: |
          mvn javadoc:javadoc
          mv target/site/javadoc/ /tmp/.

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Add new Javadoc
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          if [ -z "$(ls -A .)" ]; then
            git rm -r *
          fi
          cp -r /tmp/javadoc .
          touch .nojekyll
          git add -A
          git commit -m "update javadoc" || echo "No changes to commit"
      - name: Step5 - Push changes to gh-page branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
