name: non-regression.yml

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"

jobs:
  run-non-regression-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run all tests with coverage
        env:
          MAVEN_OPTS: "-Xms4g -Xmx4g"
        run: mvn clean test -P all-tests jacoco:report

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-summary: true
          generate-coverage-badge: true
          badges-directory: '.github/badges'
          coverage-badge-filename: 'jacoco.svg'

      - name: Deploy Badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/badges
          destination_dir: badges
          keep_files: true

      - name: Deploy Coverage Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/jacoco
          destination_dir: coverage
          keep_files: true