name: non-regression.yml
on:
  workflow_dispatch: #can be run manually

  schedule:
    - cron: "0 23 * * 0" # 23h utc

jobs:
  run-non-regression-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow automatic commit of the badge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run all tests with coverage
        env:
          MAVEN_OPTS: "-Xms4g -Xmx4g"
        run: mvn clean test -P all-tests jacoco:report

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-summary: true