name: Javadoc

on:
  push:
    branches:
      - main
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: ['3.8.5']
        java: [ '21' ]
    steps:
      - name: Step - Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Step - Build and test with Maven
        run: mvn verify

      - name: Step - Create javadoc
        run: |
          mvn javadoc:javadoc
          mv target/site/javadoc/ /tmp/.
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Step - add new javadoc
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          if [ -z "$(ls -A .)" ]; then
            git rm -r *
          fi
          cp -r /tmp/javadoc/* .
          touch .nojekyll
          git add -A
          git commit -m "update javadoc"
      - name: Step - Push changes to gh-page branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
