name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        maven: [ '3.8.5' ]
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

      - name: Clean and Compile
        run: mvn clean compile

      - name: Run fast unit tests
        run: mvn test