name: Coverage

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.8.5' ]
        java: [ '21' ]
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}